[package]
name = "skanny"
version = "0.1.0"
authors = ["Magnus Ulimoen <magnus@ulimoen.dev>"]
edition = "2018"

[dependencies]
sane-sys = { path = "sane-sys" }
image = "0.23.7"

[workspace]
members = [
    "sane-sys"
]
